version: '3.3'

services: # cada servico é um container
  backend:
    build: ./back-end
    container_name: 'app_backend'
    ports:
      - 3001:3001
    volumes:
      - ./back-end:/app/back-end
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=12345
      - DB_HOST=db  
      - DB_NAME=Ebytr
      - DB_PORT=3306
    depends_on:
      - db
    command: npm start
    restart: always

  frontend:
    build: ./front-end
    container_name: 'app_frontend'
    ports:
      - 3000:3000
    depends_on:
      - backend
    command: npm start

  db:
    image: mysql:8.0.21
    container_name: "mysql_db"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    restart: 'always'